- hosts: localhost
  vars_files:
  - ../vars/vars.yml
  - ../vars/credentials.yml

  tasks:
    - include: aws/ec2.yml  
    - include: aws/efs.yml  
    - include: aws/elasticbeanstalk.yml  
    - include: aws/rds.yml  
    - include: aws/security-groups.yml  
    - include: aws/vpc.yml

